"""Public contract for the DrumScribe music engine."""

from .audio import (
    AudioMetadata,
    AudioToolError,
    AudioValidationError,
    WaveformPeaks,
    generate_waveform_peaks,
    normalization_argv,
    normalize_audio,
    probe_audio,
    validate_audio,
    waveform_peaks_json,
)
from .exporters import (
    StandardNotationProvider,
    generate_midi,
    generate_musicxml,
    generate_pdf,
    write_midi,
    write_musicxml,
    write_pdf,
)
from .licensing import (
    LicenseStatus,
    ProviderLicense,
    UnsafeProviderError,
    require_production_safe,
    validate_provider_registry,
)
from .mapping import (
    GM_PERCUSSION_CHANNEL,
    GM_TO_INSTRUMENT,
    INSTRUMENT_TO_GM,
    NOTATION_PLACEMENT,
    canonical_instrument,
    gm_note,
)
from .models import DrumEvent, EventSource, GridSubdivision, Instrument, RawDrumHit
from .protocols import (
    BeatTrackingProvider,
    CommercialDrumTranscriptionProvider,
    DrumTranscriptionProvider,
    NotationProvider,
    QuantizationProvider,
    SourceSeparationProvider,
)
from .providers import (
    ADTOFResearchTranscriptionProvider,
    CommercialProviderConfig,
    DemucsAdapter,
    DrumScribeHybridTranscriptionProvider,
    DrumScribeRecallFusionTranscriptionProvider,
    ExternalModelError,
    ExternalModelTranscriptionProvider,
    MockBeatTrackingProvider,
    MockDrumTranscriptionProvider,
    OaFDrumsTranscriptionProvider,
    PassthroughSourceSeparationProvider,
    ResearchBeatThisTrackingProvider,
    ResearchBeatTrackingProvider,
    ResearchDependencyError,
    ResearchDrumTranscriptionProvider,
    YourMT3PlusTranscriptionProvider,
)
from .quantization import (
    DefaultQuantizer,
    QuantizationSettings,
    deduplicate_raw_hits,
    quantize_hits,
)
from .rhythm_completion import (
    RhythmCompletionResult,
    RhythmCompletionSettings,
    complete_rhythm,
)
from .tempo import MusicalPosition, TempoChange, TempoMap, TimeSignature, as_fraction

__all__ = [
    "AudioMetadata",
    "AudioToolError",
    "AudioValidationError",
    "ADTOFResearchTranscriptionProvider",
    "BeatTrackingProvider",
    "CommercialDrumTranscriptionProvider",
    "CommercialProviderConfig",
    "DefaultQuantizer",
    "DemucsAdapter",
    "DrumScribeHybridTranscriptionProvider",
    "DrumScribeRecallFusionTranscriptionProvider",
    "DrumEvent",
    "DrumTranscriptionProvider",
    "EventSource",
    "ExternalModelError",
    "ExternalModelTranscriptionProvider",
    "GM_PERCUSSION_CHANNEL",
    "GM_TO_INSTRUMENT",
    "GridSubdivision",
    "INSTRUMENT_TO_GM",
    "Instrument",
    "LicenseStatus",
    "MockBeatTrackingProvider",
    "MockDrumTranscriptionProvider",
    "MusicalPosition",
    "NOTATION_PLACEMENT",
    "NotationProvider",
    "PassthroughSourceSeparationProvider",
    "OaFDrumsTranscriptionProvider",
    "ProviderLicense",
    "QuantizationProvider",
    "QuantizationSettings",
    "RawDrumHit",
    "ResearchBeatTrackingProvider",
    "ResearchBeatThisTrackingProvider",
    "ResearchDependencyError",
    "ResearchDrumTranscriptionProvider",
    "RhythmCompletionResult",
    "RhythmCompletionSettings",
    "SourceSeparationProvider",
    "StandardNotationProvider",
    "TempoChange",
    "TempoMap",
    "TimeSignature",
    "UnsafeProviderError",
    "WaveformPeaks",
    "YourMT3PlusTranscriptionProvider",
    "as_fraction",
    "canonical_instrument",
    "complete_rhythm",
    "deduplicate_raw_hits",
    "generate_midi",
    "generate_musicxml",
    "generate_pdf",
    "generate_waveform_peaks",
    "gm_note",
    "normalization_argv",
    "normalize_audio",
    "probe_audio",
    "quantize_hits",
    "require_production_safe",
    "validate_audio",
    "validate_provider_registry",
    "waveform_peaks_json",
    "write_midi",
    "write_musicxml",
    "write_pdf",
]
