import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return <LegalPage title="Terms of use" updated="10 September 2026" intro="These beta terms describe the current DrumToScore service. Important provisions, including governing law and liability limits, still require qualified legal review before paid launch." sections={[
    { title: "Operator and contact", paragraphs: ["DrumToScore is the service name. The business address supplied for the service is 25/38 Kaveri Path, Mansarovar, Jaipur, Rajasthan, India. Contact support@drumtoscore.com for service, privacy, copyright or billing questions. The operator’s final registered legal name, entity type, postal code and tax details remain to be confirmed before paid launch."] },
    { title: "The service", paragraphs: ["DrumToScore processes audio that you provide and creates an editable first draft of a drum transcription, isolated drum audio and requested exports. Machine-generated results can be incomplete, mistimed or inaccurate. Review every result before relying on it for performance, teaching, publication or another important use.", "Features may change during beta. DrumToScore does not promise uninterrupted availability, a specific transcription score or compatibility with every recording."] },
    { title: "Eligibility and accounts", paragraphs: ["You must be legally able to agree to these terms. If you use the service for an organization, you confirm that you are authorized to act for it. You are responsible for activity under your account, access to your sign-in email and promptly reporting suspected unauthorized access."] },
    { title: "Your content and permission to process it", paragraphs: ["You retain any rights you hold in uploaded audio, project data, edits and exports. You give DrumToScore a limited, non-exclusive permission to host, copy, process and transform that material only as needed to provide, secure and maintain the service. This permission ends when the material is deleted, except for limited retention required for security, dispute handling or law.", "You are responsible for obtaining all rights needed to upload and process a recording. A transcription does not transfer rights in the underlying recording or composition, and DrumToScore cannot guarantee that an output is free of third-party rights."] },
    { title: "Acceptable use", paragraphs: ["Do not upload audio you are not authorized to process; infringe, impersonate or harm others; distribute unlawful or infringing material; access another user’s project; evade usage limits; automate abusive account creation; introduce malware; interfere with the service; or probe it for vulnerabilities without written authorization."] },
    { title: "Free use, credits and payments", paragraphs: ["The current production checkout is disabled and DrumToScore is not accepting payment. The intended offer is one free complete-song transcription per verified account followed by an optional one-time pack of ten credits; it is not a subscription.", "Before payments are enabled, checkout must identify the merchant of record, final price, currency, taxes and applicable refund terms. Paid credits must be granted only after a verified payment webhook. A failed or cancelled processing job returns the reserved credit. The separate refund policy and mandatory consumer rights also apply."] },
    { title: "Suspension and termination", paragraphs: ["You may delete projects or your account using the product controls. DrumToScore may restrict access when reasonably necessary to protect users or the service, investigate misuse, comply with law or address a material breach. A final notice and appeal process must be approved before paid launch."] },
    { title: "Unfinished legal provisions", paragraphs: ["Warranty disclaimers, limitation of liability, indemnity, dispute resolution, governing law, consumer-law disclosures, age eligibility and formal notice procedures have not been finalized. Nothing in this pre-launch text excludes rights or remedies that cannot lawfully be excluded. Obtain qualified India and cross-border counsel review before enabling payment."] },
  ]} />;
}
