import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return <LegalPage title="Terms of use" updated="12 September 2026" intro="These terms govern your use of DrumToScore. Please read them before uploading audio or buying credits." sections={[
    { title: "Operator and contact", paragraphs: ["DrumToScore is a trade and product name used by Prakhar Gupta, an individual sole proprietor in India (the “Operator”, “DrumToScore”, “we” or “us”). The business address is 25/38 Kaveri Path, Mansarovar, Jaipur, Rajasthan 302020, India. Contact support@drumtoscore.com for service, privacy, copyright or billing questions.", "The Operator is currently not registered for GST. This statement describes present registration status and is not a representation that a tax exemption will always apply. Registration obligations will be monitored as the business, customer locations and law change."] },
    { title: "The service", paragraphs: ["DrumToScore processes audio that you provide and creates an editable first draft of a drum transcription, isolated drum audio and requested exports. Machine-generated results can be incomplete, mistimed or inaccurate. Review every result before relying on it for performance, teaching, publication or another important use.", "Features may change during beta. DrumToScore does not promise uninterrupted availability, a specific transcription score or compatibility with every recording."] },
    { title: "Eligibility and accounts", paragraphs: ["You must be at least 18 years old and legally able to agree to these terms. If you use the service for an organization, you confirm that you are authorized to act for it. You are responsible for activity under your account, access to your sign-in email and promptly reporting suspected unauthorized access."] },
    { title: "Your content and permission to process it", paragraphs: ["You retain any rights you hold in uploaded audio, project data, edits and exports. You give DrumToScore a limited, non-exclusive permission to host, copy, process and transform that material only as needed to provide, secure and maintain the service. This permission ends when the material is deleted, except for limited retention required for security, dispute handling or law.", "You are responsible for obtaining all rights needed to upload and process a recording. A transcription does not transfer rights in the underlying recording or composition, and DrumToScore cannot guarantee that an output is free of third-party rights."] },
    { title: "Acceptable use", paragraphs: ["Do not upload audio you are not authorized to process; infringe, impersonate or harm others; distribute unlawful or infringing material; access another user’s project; evade usage limits; automate abusive account creation; introduce malware; interfere with the service; or probe it for vulnerabilities without written authorization."] },
    { title: "Free use, credits and payments", paragraphs: ["Each verified account receives one free complete-song transcription. After the free transcription is used, the planned paid offer is an optional one-time pack of ten transcription credits for USD 15; it is not a subscription. The exact amount, settlement currency and tax shown at checkout control if they differ from this page.", "Dodo Payments acts as merchant of record for paid checkout and handles payment processing, checkout tax calculation, receipts, refunds and chargebacks under its terms. Paid credits are granted only after a verified payment event. One credit is reserved when processing begins, and a failed or cancelled processing job returns that credit. The separate refund policy and mandatory consumer rights also apply."] },
    { title: "Suspension and termination", paragraphs: ["You may delete projects or your account using the product controls. DrumToScore may restrict or terminate access when reasonably necessary to protect users or the service, investigate misuse, comply with law or address a material breach. Where practical and lawful, we will provide notice and a reasonable opportunity to respond."] },
    { title: "AI results and warranties", paragraphs: ["DrumToScore provides machine-generated transcription drafts. To the maximum extent permitted by law, the service is provided “as is” and “as available” without a guarantee of accuracy, completeness, uninterrupted availability or fitness for a particular performance, teaching, publication or professional purpose. You must review and correct outputs before relying on them. Nothing here excludes a warranty or consumer remedy that applicable law does not permit us to exclude."] },
    { title: "Limitation of liability", paragraphs: ["To the maximum extent permitted by law, DrumToScore is not liable for indirect, incidental, special or consequential loss, loss of profits, lost opportunities or loss caused by reliance on an unreviewed transcription. DrumToScore’s total liability arising from the service will not exceed the amount you paid for the service during the 12 months before the event giving rise to the claim.", "These limits do not apply where liability cannot lawfully be limited, including applicable liability for fraud, wilful misconduct, death or personal injury, or mandatory consumer rights."] },
    { title: "Governing law", paragraphs: ["These terms are governed by the laws of India and applicable laws of Rajasthan. Subject to any mandatory consumer forum or jurisdiction that cannot be excluded, courts located in Jaipur, Rajasthan will have jurisdiction over disputes. Before formal proceedings, please contact support@drumtoscore.com so the parties can try to resolve the issue in good faith."] },
    { title: "Changes and legal review", paragraphs: ["We may update these terms when the service, prices or law changes. Material changes will be dated on this page and, where appropriate, communicated in the product or by email. These terms are intended as a conservative launch baseline and should still receive qualified India and cross-border legal review as the business expands."] },
  ]} />;
}
