import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy policy" };

export default function PrivacyPage() {
  return <LegalPage title="Privacy policy" updated="12 September 2026" intro="This policy describes how DrumToScore handles personal data and customer audio." sections={[
    { title: "Who is responsible", paragraphs: ["DrumToScore is a trade and product name used by Prakhar Gupta, an individual sole proprietor in India and the operator responsible for this service. Contact privacy@drumtoscore.com about privacy or data requests. The business address is 25/38 Kaveri Path, Mansarovar, Jaipur, Rajasthan 302020, India."] },
    { title: "What we collect", paragraphs: ["We collect the email address used for passwordless sign-in; account, credit and consent settings; private project metadata; uploaded audio; generated drum stems, transcriptions, edits and exports; feedback; and operational records such as request identifiers, timestamps, job status and security events.", "The service uses a necessary HTTP-only session cookie. Rate limiting uses a one-way keyed representation of the network address rather than storing the raw address in the rate-limit key. Error and performance monitoring is configured not to send default personal information, but diagnostic events may still contain technical request context."] },
    { title: "Why we process data", paragraphs: ["Data is processed to authenticate users, accept and validate uploads, run transcription jobs, synchronize and export projects, enforce credits, prevent abuse, diagnose failures, secure the service and respond to support or legal requests. Before paid launch, counsel must document the applicable legal basis for each purpose and jurisdiction."] },
    { title: "How audio is used", paragraphs: ["Audio is processed only to provide the feature you request. Projects are private and are not indexed or automatically published. Uploads, transcriptions and corrections are not used for model training unless you separately opt in; the model-improvement setting defaults to off. Opt-in alone does not move data into training: a separately governed dataset review is still required."] },
    { title: "Service providers and locations", paragraphs: ["Cloudflare serves the website and edge proxy; Oracle Cloud in Mumbai runs the API and transcription worker; Neon and Upstash in AWS Ohio provide database, private object storage and queue state; Resend sends sign-in email; and Sentry receives configured error and performance telemetry. GitHub hosts source code and performs public-endpoint uptime checks without receiving customer audio through that check.", "These providers can process data outside your country. Contracts, data-processing terms, subprocessor records and the transfer mechanism required for each launch jurisdiction still need legal review. When checkout is enabled, Dodo Payments will receive account, order, billing, tax and payment-related data as merchant of record. It does not receive uploaded audio through the checkout integration."] },
    { title: "Retention and deletion", paragraphs: ["Active-project audio remains in private object storage while the project exists. Signed upload and download links expire after about 10 minutes. Unprocessed or replaced uploads are scheduled for deletion after 24 hours. Generated export files are scheduled for deletion after seven days and can be generated again.", "Inactive anonymous accounts and projects are scheduled for deletion after 24 hours. Deleting a signed-in project immediately revokes normal access and provides a seven-day recovery window before associated media is purged. Account deletion revokes sessions, removes the email address from the account record and requests immediate deletion of project media and exports; opaque audit or tombstone records may remain for security, integrity or legal obligations. Cleanup is retryable if a storage provider is temporarily unavailable."] },
    { title: "Your choices", paragraphs: ["Account Settings lets you export project and account metadata, keep model-improvement participation off, delete a project and request permanent account deletion. You may also email the contact above to request access, correction, deletion or another applicable privacy right. Identity verification may be required before fulfilling a request."], bullets: ["No public project gallery", "No raw audio or filenames intentionally added to product analytics", "No sale of customer audio", "No automatic model training from uploads"] },
    { title: "Security and children", paragraphs: ["DrumToScore uses private storage, short-lived signed links, encrypted transport, restricted production secrets and access controls. No internet service can guarantee absolute security. The service is intended only for people aged 18 or older, and we do not knowingly collect personal data from children."] },
    { title: "Policy changes and contact", paragraphs: ["Material changes should be dated here and, when appropriate, communicated in the product or by email. Send privacy questions or requests to privacy@drumtoscore.com. A response timetable and jurisdiction-specific rights section remain launch items."] },
  ]} />;
}
