"""initial schema

Revision ID: 6153412384df
Revises: 
Create Date: 2026-08-29 10:01:55.636612
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6153412384df'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('magic_links',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_token_hash'), ['token_hash'], unique=True)

    op.create_table('product_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('kind', sa.Enum('ANONYMOUS', 'REGISTERED', name='userkind', native_enum=False, length=64), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False, length=64), nullable=False),
    sa.Column('entitlement', sa.Enum('FREE_BETA', name='entitlement', native_enum=False, length=64), nullable=False),
    sa.Column('allow_model_improvement', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UPLOADING', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'CANCELLED', name='projectstatus', native_enum=False, length=64), nullable=False),
    sa.Column('original_asset_id', sa.Uuid(), nullable=True),
    sa.Column('active_transcription_id', sa.Uuid(), nullable=True),
    sa.Column('edit_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_projects_owner_title', ['owner_id', 'title'], unique=False)
        batch_op.create_index('ix_projects_owner_updated', ['owner_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('audio_assets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('ORIGINAL', 'NORMALIZED', 'DRUM_STEM', 'WAVEFORM_PEAKS', 'SCORE_SOURCE', 'EXPORT', name='assetkind', native_enum=False, length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING_UPLOAD', 'UPLOADED', 'VERIFIED', 'DELETING', 'DELETED', 'REJECTED', name='assetstatus', native_enum=False, length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_assets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_assets_project_id'), ['project_id'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('RECEIVED', 'VALIDATING', 'NORMALIZING', 'SEPARATING_DRUMS', 'TRANSCRIBING', 'DETECTING_BEATS', 'QUANTIZING', 'GENERATING_SCORE', 'FINALIZING', 'READY', 'FAILED', 'CANCELLED', name='jobstage', native_enum=False, length=64), nullable=False),
    sa.Column('last_completed_stage', sa.Enum('RECEIVED', 'VALIDATING', 'NORMALIZING', 'SEPARATING_DRUMS', 'TRANSCRIBING', 'DETECTING_BEATS', 'QUANTIZING', 'GENERATING_SCORE', 'FINALIZING', 'READY', 'FAILED', 'CANCELLED', name='jobstage', native_enum=False, length=64), nullable=True),
    sa.Column('approximate_progress', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker', sa.String(length=255), nullable=True),
    sa.Column('provider_versions', sa.JSON(), nullable=False),
    sa.Column('stage_timings', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.Enum('INVALID_AUDIO', 'UNSUPPORTED_CODEC', 'AUDIO_TOO_LONG', 'AUDIO_TOO_LARGE', 'SEPARATION_FAILED', 'TRANSCRIPTION_FAILED', 'BEAT_TRACKING_FAILED', 'SCORE_GENERATION_FAILED', 'WORKER_TIMEOUT', 'INTERNAL_ERROR', name='joberrorcode', native_enum=False, length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_job_project_idempotency')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('user_feedback',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_runs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('model_hash', sa.String(length=128), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('hardware_metadata', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_job_id'), ['job_id'], unique=False)

    op.create_table('transcriptions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=True),
    sa.Column('tempo_bpm', sa.Float(), nullable=False),
    sa.Column('time_signature_numerator', sa.Integer(), nullable=False),
    sa.Column('time_signature_denominator', sa.Integer(), nullable=False),
    sa.Column('tempo_map', sa.JSON(), nullable=False),
    sa.Column('quality_summary', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcriptions_project_id'), ['project_id'], unique=False)

    op.create_table('drum_events',
    sa.Column('transcription_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('instrument', sa.Enum('KICK', 'SNARE', 'CROSS_STICK', 'CLOSED_HIHAT', 'OPEN_HIHAT', 'PEDAL_HIHAT', 'RIDE', 'RIDE_BELL', 'CRASH', 'HIGH_TOM', 'MID_TOM', 'LOW_TOM', 'FLOOR_TOM', name='instrument', native_enum=False, length=64), nullable=False),
    sa.Column('onset_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('AI', 'USER', 'IMPORT', name='eventsource', native_enum=False, length=64), nullable=False),
    sa.Column('beat_position', sa.Float(), nullable=False),
    sa.Column('measure_index', sa.Integer(), nullable=False),
    sa.Column('subdivision', sa.String(length=32), nullable=False),
    sa.Column('quantized_onset', sa.Float(), nullable=False),
    sa.Column('manually_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drum_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drum_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drum_events_transcription_id'), ['transcription_id'], unique=False)
        batch_op.create_index('ix_events_project_measure', ['project_id', 'measure_index'], unique=False)
        batch_op.create_index('ix_events_transcription_onset', ['transcription_id', 'quantized_onset'], unique=False)

    op.create_table('exports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('transcription_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('MIDI', 'MUSICXML', 'PDF', name='exportformat', native_enum=False, length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'READY', 'FAILED', 'CANCELLED', name='exportstatus', native_enum=False, length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_export_idempotency'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_project_id'), ['project_id'], unique=False)

    op.create_table('transcription_revisions',
    sa.Column('transcription_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('AI_ORIGINAL', 'AUTOSAVE', 'MANUAL', 'RESTORE', name='revisionkind', native_enum=False, length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcription_id', 'sequence', name='uq_revision_sequence')
    )
    with op.batch_alter_table('transcription_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcription_revisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcription_revisions_transcription_id'), ['transcription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcription_revisions_transcription_id'))
        batch_op.drop_index(batch_op.f('ix_transcription_revisions_project_id'))

    op.drop_table('transcription_revisions')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_project_id'))

    op.drop_table('exports')
    with op.batch_alter_table('drum_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_transcription_onset')
        batch_op.drop_index('ix_events_project_measure')
        batch_op.drop_index(batch_op.f('ix_drum_events_transcription_id'))
        batch_op.drop_index(batch_op.f('ix_drum_events_project_id'))

    op.drop_table('drum_events')
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcriptions_project_id'))

    op.drop_table('transcriptions')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_job_id'))

    op.drop_table('model_runs')
    op.drop_table('user_feedback')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_project_id'))
        batch_op.drop_index('ix_jobs_project_created')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_audio_assets_kind'))

    op.drop_table('audio_assets')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index('ix_projects_owner_updated')
        batch_op.drop_index('ix_projects_owner_title')
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    op.drop_table('users')
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_product_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_product_events_name'))

    op.drop_table('product_events')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_token_hash'))
        batch_op.drop_index(batch_op.f('ix_magic_links_expires_at'))
        batch_op.drop_index(batch_op.f('ix_magic_links_email'))

    op.drop_table('magic_links')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
