"""add data integrity constraints

Revision ID: d90d268d92dc
Revises: 6153412384df
Create Date: 2026-08-29 10:12:37.470490
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd90d268d92dc'
down_revision: str | None = '6153412384df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.create_check_constraint('asset_duration', 'duration_seconds IS NULL OR duration_seconds >= 0')
        batch_op.create_check_constraint('asset_size', 'size_bytes IS NULL OR size_bytes >= 0')

    with op.batch_alter_table('drum_events', schema=None) as batch_op:
        batch_op.create_check_constraint('event_confidence', 'confidence IS NULL OR (confidence >= 0 AND confidence <= 1)')
        batch_op.create_check_constraint('event_duration', 'duration_seconds > 0')
        batch_op.create_check_constraint('event_measure', 'measure_index >= 0')
        batch_op.create_check_constraint('event_onset', 'onset_seconds >= 0')
        batch_op.create_check_constraint('event_quantized_onset', 'quantized_onset >= 0')
        batch_op.create_check_constraint('event_velocity', 'velocity >= 1 AND velocity <= 127')

    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_check_constraint('job_progress', 'approximate_progress >= 0 AND approximate_progress <= 100')
        batch_op.create_check_constraint('job_retry_count', 'retry_count >= 0')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_check_constraint('project_duration', 'duration_seconds IS NULL OR duration_seconds >= 0')
        batch_op.create_check_constraint('project_edit_version', 'edit_version >= 0')

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_check_constraint('time_signature_denominator', 'time_signature_denominator IN (1, 2, 4, 8, 16, 32)')
        batch_op.create_check_constraint('time_signature_numerator', 'time_signature_numerator >= 1')
        batch_op.create_check_constraint('transcription_tempo', 'tempo_bpm >= 20 AND tempo_bpm <= 400')
        batch_op.create_check_constraint('transcription_version', 'version >= 1')

    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_check_constraint('feedback_rating', 'rating IS NULL OR (rating >= 1 AND rating <= 5)')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_constraint('feedback_rating', type_='check')

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_constraint('transcription_version', type_='check')
        batch_op.drop_constraint('transcription_tempo', type_='check')
        batch_op.drop_constraint('time_signature_numerator', type_='check')
        batch_op.drop_constraint('time_signature_denominator', type_='check')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('project_edit_version', type_='check')
        batch_op.drop_constraint('project_duration', type_='check')

    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('job_retry_count', type_='check')
        batch_op.drop_constraint('job_progress', type_='check')

    with op.batch_alter_table('drum_events', schema=None) as batch_op:
        batch_op.drop_constraint('event_velocity', type_='check')
        batch_op.drop_constraint('event_quantized_onset', type_='check')
        batch_op.drop_constraint('event_onset', type_='check')
        batch_op.drop_constraint('event_measure', type_='check')
        batch_op.drop_constraint('event_duration', type_='check')
        batch_op.drop_constraint('event_confidence', type_='check')

    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_constraint('asset_size', type_='check')
        batch_op.drop_constraint('asset_duration', type_='check')

    # ### end Alembic commands ###
