import hashlib
import json
import wave
from pathlib import Path

import numpy as np
import pytest
from drumscribe_music import Instrument

from drumscribe_ml.calibration import calibrate_confidence
from drumscribe_ml.checkpoint_eval import _evidence_level
from drumscribe_ml.ensemble import (
    CheckpointReference,
    EnsembleConfig,
    EnsembleRule,
    StackedEnsembleConfig,
    StackedEnsembleRule,
    blend_probabilities,
    blend_stacked_probabilities,
    decode_probabilities,
    decode_stacked_probabilities,
)
from drumscribe_ml.lifecycle import (
    PreparationConfig,
    augmentation_recipe,
    prepare_dataset,
    read_pcm_wav,
)
from drumscribe_ml.manifest import DatasetLicense, DatasetManifest, DatasetSource, DatasetTrack
from drumscribe_ml.training import (
    TRAINING_CLASSES,
    TrainingConfig,
    TrainingError,
    _apply_family_competition,
    _binary_focal_loss_with_logits,
    _calibration_peak_f1,
    _calibration_peak_tracks,
    _dilate_targets,
    _epoch_records,
    _family_classification_loss,
    _match_frames,
    _mixup_training_batch,
    _peak_distance_candidates,
    _peak_frames,
    _positive_class_weights,
    _resume_validation_compatible,
    _threshold_candidates,
    _training_batches,
    build_model,
    experiment_metadata,
)


def _write_wav(path: Path, *, frequency: float = 110) -> None:
    sample_rate = 8_000
    timeline = np.arange(sample_rate, dtype=np.float32) / sample_rate
    samples = (np.sin(2 * np.pi * frequency * timeline) * 0.25 * 32767).astype("<i2")
    path.parent.mkdir(parents=True)
    with wave.open(str(path), "wb") as target:
        target.setnchannels(1)
        target.setsampwidth(2)
        target.setframerate(sample_rate)
        target.writeframes(samples.tobytes())


def _write_24_bit_wav(path: Path) -> None:
    values = np.array([-8_388_608, -1, 0, 1, 8_388_607], dtype=np.int64)
    encoded = (values & 0xFFFFFF).astype(np.uint32)
    octets = np.column_stack(
        (encoded & 0xFF, (encoded >> 8) & 0xFF, (encoded >> 16) & 0xFF)
    ).astype(np.uint8)
    with wave.open(str(path), "wb") as target:
        target.setnchannels(1)
        target.setsampwidth(3)
        target.setframerate(8_000)
        target.writeframes(octets.tobytes())


def _manifest(root: Path) -> DatasetManifest:
    audio = root / "audio" / "take.wav"
    annotation = root / "annotations" / "take.json"
    _write_wav(audio)
    annotation.parent.mkdir(parents=True)
    annotation.write_text(
        json.dumps(
            [
                {"midiNote": 36, "onsetSeconds": 0.1, "velocity": 100},
                {"label": "snare", "onsetSeconds": 0.5, "velocity": 88},
            ]
        ),
        encoding="utf-8",
    )
    license_record = DatasetLicense(
        "CC0-1.0",
        "https://creativecommons.org/publicdomain/zero/1.0/",
        True,
        "Generated by the DrumScribe test suite",
    )
    return DatasetManifest(
        DatasetSource("Generated test audio", "1", "https://example.test", license_record),
        (
            DatasetTrack(
                "take",
                "performance",
                "audio/take.wav",
                "annotations/take.json",
                1,
                hashlib.sha256(audio.read_bytes()).hexdigest(),
            ),
        ),
    )


def test_preparation_is_reproducible_and_caches_real_features(tmp_path):
    dataset = tmp_path / "dataset"
    manifest = _manifest(dataset)
    config = PreparationConfig(
        seed="release-1",
        sample_rate=8_000,
        frame_length=256,
        hop_length=80,
        mel_bands=24,
        augmentation_variants=1,
    )
    prepared = prepare_dataset(
        manifest,
        dataset_root=dataset,
        output_root=tmp_path / "prepared",
        config=config,
    )
    payload = json.loads(prepared.read_text())
    assert len(payload["records"]) == 2
    assert payload["records"][0]["groupId"] == "performance"
    canonical = json.loads(Path(payload["records"][0]["annotationPath"]).read_text())
    assert [row["instrument"] for row in canonical["events"]] == ["KICK", "SNARE"]
    features = np.load(payload["records"][0]["featurePath"])["features"]
    assert features.ndim == 2 and features.shape[1] == 24
    original, _ = read_pcm_wav(dataset / "audio/take.wav")
    augmented, _ = read_pcm_wav(Path(payload["records"][1]["audioPath"]))
    assert not np.array_equal(original, augmented)
    assert augmentation_recipe("release-1", "take", 1) == augmentation_recipe(
        "release-1", "take", 1
    )


def test_calibration_and_training_metadata_are_versioned(tmp_path):
    logits = np.array([[3.0, -2.0], [-2.0, 2.0], [1.0, -1.0]])
    targets = np.array([[1, 0], [0, 1], [1, 0]])
    result = calibrate_confidence(logits, targets)
    assert result.macro_f1 == pytest.approx(1)
    assert len(result.thresholds) == 2
    config = TrainingConfig("prepared.json", str(tmp_path), "drumscribe-events-0.1.0")
    metadata = experiment_metadata(
        config,
        {"dataset": {"name": "test", "version": "1"}, "datasetManifestHash": "abc"},
    )
    assert metadata["modelVersion"] == "drumscribe-events-0.1.0"
    assert metadata["datasetManifestHash"] == "abc"
    with pytest.raises(TrainingError):
        TrainingConfig("prepared.json", str(tmp_path), "bad/version")
    moe = TrainingConfig(
        "prepared.json",
        str(tmp_path),
        "drumscribe-events-moe-0.1.0",
        architecture="spectral_moe",
        moe_experts=8,
        moe_top_k=2,
    )
    assert moe.architecture == "spectral_moe"
    with pytest.raises(TrainingError, match="top-k"):
        TrainingConfig(
            "prepared.json",
            str(tmp_path),
            "invalid-moe",
            architecture="spectral_moe",
            moe_experts=2,
            moe_top_k=3,
        )
    resumed = TrainingConfig(
        "prepared.json",
        str(tmp_path),
        "fine-tuned",
        resume_checkpoint="best.pt",
        resume_learning_rate=0.0001,
    )
    assert resumed.resume_learning_rate == pytest.approx(0.0001)
    with pytest.raises(TrainingError, match="resume_learning_rate"):
        TrainingConfig(
            "prepared.json",
            str(tmp_path),
            "invalid-resume-rate",
            resume_checkpoint="best.pt",
            resume_learning_rate=0.001,
        )
    targeted = TrainingConfig(
        "prepared.json",
        str(tmp_path),
        "targeted",
        family_classification_loss_weight=0.2,
        positive_weight_exponent=0.5,
    )
    assert targeted.family_classification_loss_weight == pytest.approx(0.2)
    assert targeted.positive_weight_exponent == pytest.approx(0.5)
    with pytest.raises(TrainingError, match="positive weight exponent"):
        TrainingConfig(
            "prepared.json", str(tmp_path), "invalid-weight-exponent", positive_weight_exponent=2
        )
    focused = TrainingConfig(
        "prepared.json",
        str(tmp_path),
        "focused",
        onset_class_loss_multipliers={"PEDAL_HIHAT": 2.5},
    )
    assert focused.onset_class_loss_multipliers == {"PEDAL_HIHAT": 2.5}
    with pytest.raises(TrainingError, match="unknown onset loss multiplier"):
        TrainingConfig(
            "prepared.json",
            str(tmp_path),
            "invalid-focused-class",
            onset_class_loss_multipliers={"COWBELL": 2},
        )
    with pytest.raises(TrainingError, match="in \\(0, 10\\]"):
        TrainingConfig(
            "prepared.json",
            str(tmp_path),
            "invalid-focused-weight",
            onset_class_loss_multipliers={"PEDAL_HIHAT": 0},
        )
    focal = TrainingConfig("prepared.json", str(tmp_path), "focal", onset_focal_gamma=1.5)
    assert focal.onset_focal_gamma == pytest.approx(1.5)
    with pytest.raises(TrainingError, match="focal gamma"):
        TrainingConfig("prepared.json", str(tmp_path), "invalid-focal", onset_focal_gamma=6)


def test_binary_focal_loss_preserves_bce_at_zero_and_downweights_easy_frames():
    import torch
    import torch.nn.functional as functional

    logits = torch.tensor([[5.0, -5.0], [0.2, -0.2]])
    targets = torch.tensor([[1.0, 0.0], [1.0, 0.0]])
    positive_weights = torch.tensor([2.0, 3.0])
    baseline = functional.binary_cross_entropy_with_logits(
        logits, targets, pos_weight=positive_weights, reduction="none"
    )
    focal_zero = _binary_focal_loss_with_logits(
        logits, targets, pos_weight=positive_weights, gamma=0
    )
    focal = _binary_focal_loss_with_logits(logits, targets, pos_weight=positive_weights, gamma=2)
    assert torch.equal(focal_zero, baseline)
    assert torch.all(focal < baseline)
    assert focal[0].sum() < focal[1].sum()


def test_training_targets_and_validation_are_onset_tolerant_and_multilabel():
    targets = np.zeros((8, 2), dtype=np.float32)
    targets[3, :] = 1
    dilated = _dilate_targets(targets, 1)
    assert dilated[:, 0].tolist() == [0, 0, 1, 1, 1, 0, 0, 0]
    probabilities = np.array([0.1, 0.6, 0.8, 0.7, 0.2])
    assert _peak_frames(probabilities, threshold=0.5) == [2]
    assert _match_frames([4, 10], [5, 20], tolerance=2) == (1, 1, 1)
    assert set(TRAINING_CLASSES) == set(Instrument)
    candidates = _threshold_candidates()
    assert candidates[0] == pytest.approx(0.05)
    assert candidates[-1] == pytest.approx(0.995)
    assert len(candidates) == len(set(candidates.tolist()))
    assert _peak_distance_candidates() == (1, 2, 3, 4, 5, 6, 8)


def test_peak_frames_suppress_nearby_duplicates_by_probability():
    probabilities = np.array([0.1, 0.8, 0.2, 0.9, 0.1, 0.7, 0.1])
    assert _peak_frames(probabilities, threshold=0.5) == [1, 3, 5]
    assert _peak_frames(probabilities, threshold=0.5, minimum_distance_frames=3) == [3]
    with pytest.raises(TrainingError, match="minimum peak distance"):
        _peak_frames(probabilities, threshold=0.5, minimum_distance_frames=0)


def test_cached_calibration_peaks_match_direct_evaluation():
    class_index = 0
    probabilities = np.array([[0.1], [0.8], [0.2], [0.9], [0.1]], dtype=np.float32)
    targets = np.array([[0], [1], [0], [1], [0]], dtype=np.float32)
    evaluated = [(probabilities, targets)]
    tracks = _calibration_peak_tracks(
        evaluated,
        class_index=class_index,
        peak_distance_frames=1,
    )
    assert _calibration_peak_f1(
        tracks,
        threshold=0.5,
        tolerance_frames=0,
    ) == pytest.approx(1)


def test_family_competition_keeps_strongest_hihat_and_ride_articulation():
    probabilities = np.zeros((2, len(TRAINING_CLASSES)), dtype=np.float32)
    class_index = {instrument: index for index, instrument in enumerate(TRAINING_CLASSES)}
    probabilities[0, class_index[Instrument.CLOSED_HIHAT]] = 0.8
    probabilities[0, class_index[Instrument.OPEN_HIHAT]] = 0.7
    probabilities[0, class_index[Instrument.PEDAL_HIHAT]] = 0.6
    probabilities[1, class_index[Instrument.RIDE]] = 0.4
    probabilities[1, class_index[Instrument.RIDE_BELL]] = 0.9
    probabilities[0, class_index[Instrument.KICK]] = 0.5
    competed = _apply_family_competition(probabilities)
    assert competed[0, class_index[Instrument.CLOSED_HIHAT]] == pytest.approx(0.8)
    assert competed[0, class_index[Instrument.OPEN_HIHAT]] == 0
    assert competed[0, class_index[Instrument.PEDAL_HIHAT]] == 0
    assert competed[1, class_index[Instrument.RIDE]] == 0
    assert competed[1, class_index[Instrument.RIDE_BELL]] == pytest.approx(0.9)
    assert competed[0, class_index[Instrument.KICK]] == pytest.approx(0.5)


def test_family_classification_loss_rewards_correct_articulation():
    torch = pytest.importorskip("torch")
    class_index = {instrument: index for index, instrument in enumerate(TRAINING_CLASSES)}
    targets = torch.zeros((1, 2, len(TRAINING_CLASSES)))
    targets[0, 0, class_index[Instrument.CLOSED_HIHAT]] = 1
    targets[0, 1, class_index[Instrument.RIDE_BELL]] = 1
    correct = torch.zeros_like(targets)
    correct[0, 0, class_index[Instrument.CLOSED_HIHAT]] = 4
    correct[0, 0, class_index[Instrument.OPEN_HIHAT]] = -4
    correct[0, 1, class_index[Instrument.RIDE_BELL]] = 4
    correct[0, 1, class_index[Instrument.RIDE]] = -4
    incorrect = -correct
    assert _family_classification_loss(correct, targets) < _family_classification_loss(
        incorrect, targets
    )


def test_pcm_reader_decodes_signed_24_bit_audio(tmp_path):
    path = tmp_path / "24-bit.wav"
    _write_24_bit_wav(path)
    samples, sample_rate = read_pcm_wav(path)
    assert sample_rate == 8_000
    assert samples[:, 0].tolist() == pytest.approx([-1, -1 / 8_388_608, 0, 1 / 8_388_608, 1])


def test_training_batches_pad_and_mask_only_real_frames():
    features = np.ones((5, 3), dtype=np.float32)
    onsets = np.zeros((5, 2), dtype=np.float32)
    velocities = np.zeros_like(onsets)
    batches = list(_training_batches(features, onsets, velocities, 3, 2))
    feature_batch, _, _, valid = batches[0]
    assert feature_batch.shape == (2, 3, 3)
    assert valid[:, :, 0].tolist() == [[1, 1, 1], [1, 1, 0]]


def test_training_mixup_is_deterministic_training_only_composition():
    features = np.array([[[1.0]], [[3.0]]], dtype=np.float32)
    onsets = np.array([[[1.0]], [[0.0]]], dtype=np.float32)
    velocities = np.array([[[0.8]], [[0.0]]], dtype=np.float32)
    valid = np.ones((2, 1, 1), dtype=np.float32)
    first = _mixup_training_batch(
        features,
        onsets,
        velocities,
        valid,
        probability=1,
        alpha=0.4,
        rng=np.random.default_rng(42),
    )
    repeated = _mixup_training_batch(
        features,
        onsets,
        velocities,
        valid,
        probability=1,
        alpha=0.4,
        rng=np.random.default_rng(42),
    )
    for actual, expected in zip(first, repeated, strict=True):
        assert actual == pytest.approx(expected)
    assert first[0][0, 0, 0] != pytest.approx(features[0, 0, 0])
    assert first[1].min() >= 0 and first[1].max() <= 1


def test_positive_weight_exponent_can_temper_rare_class_pressure(monkeypatch):
    targets = np.zeros((101, len(TRAINING_CLASSES)), dtype=np.float32)
    targets[0, 0] = 1
    monkeypatch.setattr(
        "drumscribe_ml.training._load_training_record",
        lambda record: (np.zeros((101, 2), dtype=np.float32), targets, targets),
    )
    full = _positive_class_weights([{"trackId": "fixture"}], exponent=1)
    tempered = _positive_class_weights([{"trackId": "fixture"}], exponent=0.5)
    assert full[0] == pytest.approx(100)
    assert tempered[0] == pytest.approx(10)
    assert tempered[1] == pytest.approx(1)


def test_training_record_order_is_epoch_specific_and_reproducible():
    records = [
        {"groupId": f"group-{index}", "trackId": f"track-{index}", "variant": "original"}
        for index in range(12)
    ]
    first = _epoch_records(records, seed=42, epoch=3)
    repeated = _epoch_records(records, seed=42, epoch=3)
    next_epoch = _epoch_records(records, seed=42, epoch=4)
    assert first == repeated
    assert first != next_epoch
    assert records == [
        {"groupId": f"group-{index}", "trackId": f"track-{index}", "variant": "original"}
        for index in range(12)
    ]


def test_resume_validation_state_requires_the_same_prepared_dataset(tmp_path):
    current = tmp_path / "current.json"
    previous = tmp_path / "previous.json"
    assert _resume_validation_compatible(
        {"preparedDatasetSha256": "same"},
        prepared_path=current,
        prepared_dataset_sha256="same",
    )
    assert not _resume_validation_compatible(
        {"preparedDatasetSha256": "different"},
        prepared_path=current,
        prepared_dataset_sha256="same",
    )
    assert _resume_validation_compatible(
        {"configuration": {"prepared_dataset": str(current)}},
        prepared_path=current,
        prepared_dataset_sha256="same",
    )
    assert not _resume_validation_compatible(
        {"configuration": {"prepared_dataset": str(previous)}},
        prepared_path=current,
        prepared_dataset_sha256="same",
    )


def test_checkpoint_evidence_labels_keep_test_and_training_distinct():
    assert _evidence_level(evaluation_only=False, split="test") == "natural_sealed_test"
    assert _evidence_level(evaluation_only=False, split="validation") == "natural_validation"
    assert _evidence_level(evaluation_only=False, split="train") == "natural_training_diagnostic"
    assert (
        _evidence_level(evaluation_only=True, split="validation")
        == "synthetic_reserved_validation_probe"
    )
    assert (
        _evidence_level(evaluation_only=True, synthetic=True, split="test")
        == "synthetic_reserved_test"
    )
    assert (
        _evidence_level(evaluation_only=False, synthetic=True, split="validation")
        == "synthetic_validation"
    )


def test_oaf_style_model_preserves_frame_alignment():
    torch = pytest.importorskip("torch")
    config = TrainingConfig(
        "prepared.json",
        "/tmp",
        "oaf-shape",
        architecture="oaf_cnn",
        hidden_size=32,
    )
    model = build_model(config, mel_bands=80, class_count=len(TRAINING_CLASSES))
    onsets, velocities = model(torch.zeros((2, 127, 80)))
    assert onsets.shape == (2, 127, len(TRAINING_CLASSES))
    assert velocities.shape == onsets.shape


def test_ensemble_blends_and_decodes_with_fixed_rules():
    class_count = len(TRAINING_CLASSES)
    primary = np.full((5, class_count), 0.1, dtype=np.float32)
    secondary = np.full((5, class_count), 0.2, dtype=np.float32)
    rules = {
        instrument.value: EnsembleRule(
            strategy="convex",
            secondary_weight=0.25,
            threshold=0.15,
            peak_distance_frames=1,
        )
        for instrument in TRAINING_CLASSES
    }
    primary[2, 0] = 0.8
    secondary[2, 0] = 0.6
    rules[TRAINING_CLASSES[1].value] = EnsembleRule(
        strategy="maximum", threshold=0.19, peak_distance_frames=1
    )
    rules[TRAINING_CLASSES[2].value] = EnsembleRule(
        strategy="noisy_or", threshold=0.27, peak_distance_frames=1
    )
    blended = blend_probabilities(primary, secondary, rules)
    assert blended[2, 0] == pytest.approx(0.75)
    assert blended[0, 1] == pytest.approx(0.2)
    assert blended[0, 2] == pytest.approx(0.28)
    decoded = decode_probabilities(blended, rules)
    assert decoded[TRAINING_CLASSES[0].value] == [2]
    assert decoded[TRAINING_CLASSES[1].value] == [4]


def test_ensemble_config_requires_rules_for_every_class():
    reference = CheckpointReference(model_version="fixture", sha256="0" * 64)
    with pytest.raises(TrainingError, match="cover every class"):
        EnsembleConfig(
            model_version="fixture",
            primary=reference,
            secondary=reference,
            rules={},
        )


def test_stacked_ensemble_fuses_named_models_and_temporal_scores():
    shape = (5, len(TRAINING_CLASSES))
    first = np.full(shape, 0.1, dtype=np.float32)
    second = np.full(shape, 0.2, dtype=np.float32)
    first[2, 0] = 0.8
    second[2, 0] = 0.6
    rules = {
        instrument.value: StackedEnsembleRule(
            strategy="convex",
            model_weights={"first": 1},
            threshold=0.5,
            peak_distance_frames=1,
        )
        for instrument in TRAINING_CLASSES
    }
    rules[TRAINING_CLASSES[0].value] = StackedEnsembleRule(
        strategy="convex",
        model_weights={"first": 0.5, "second": 0.5},
        threshold=0.2,
        peak_distance_frames=1,
        temporal_kernel=(1, 2, 1),
        temporal_blend=1,
    )
    rules[TRAINING_CLASSES[1].value] = StackedEnsembleRule(
        strategy="logit",
        model_weights={"first": 1.5, "second": -0.5},
        threshold=0.1,
        peak_distance_frames=1,
    )
    rules[TRAINING_CLASSES[2].value] = StackedEnsembleRule(
        strategy="maximum",
        model_weights={"first": 1, "second": 1},
        threshold=0.1,
        peak_distance_frames=1,
    )
    rules[TRAINING_CLASSES[3].value] = StackedEnsembleRule(
        strategy="convex",
        model_weights={"first": 1},
        threshold=0.1,
        peak_distance_frames=1,
        post_blend_model="second",
        post_blend_strategy="logit",
        post_blend_weight=0.25,
    )
    output = blend_stacked_probabilities({"first": first, "second": second}, rules)
    assert output[2, 0] == pytest.approx(0.425)
    expected_logit = 1 / (1 + np.exp(-(1.5 * np.log(0.1 / 0.9) - 0.5 * np.log(0.2 / 0.8))))
    assert output[0, 1] == pytest.approx(expected_logit)
    assert output[0, 2] == pytest.approx(0.2)
    expected_post_blend = 1 / (1 + np.exp(-(0.75 * np.log(0.1 / 0.9) + 0.25 * np.log(0.2 / 0.8))))
    assert output[0, 3] == pytest.approx(expected_post_blend)


def test_stacked_decoder_resolves_exact_frame_exclusive_family_conflicts():
    shape = (5, len(TRAINING_CLASSES))
    probabilities = np.full(shape, 0.1, dtype=np.float32)
    rules = {
        instrument.value: StackedEnsembleRule(
            strategy="convex",
            model_weights={"base": 1},
            threshold=0.5,
            peak_distance_frames=1,
        )
        for instrument in TRAINING_CLASSES
    }
    closed_index = TRAINING_CLASSES.index(Instrument.CLOSED_HIHAT)
    open_index = TRAINING_CLASSES.index(Instrument.OPEN_HIHAT)
    probabilities[2, closed_index] = 0.8
    probabilities[2, open_index] = 0.9

    independent = decode_stacked_probabilities(probabilities, rules)
    assert independent[Instrument.CLOSED_HIHAT.value] == [2]
    assert independent[Instrument.OPEN_HIHAT.value] == [2]

    resolved = decode_stacked_probabilities(
        probabilities, rules, family_conflict_margins={"HIHAT": 0.5}
    )
    assert resolved[Instrument.CLOSED_HIHAT.value] == []
    assert resolved[Instrument.OPEN_HIHAT.value] == [2]

    ambiguous = decode_stacked_probabilities(
        probabilities, rules, family_conflict_margins={"HIHAT": 1.0}
    )
    assert ambiguous[Instrument.CLOSED_HIHAT.value] == [2]
    assert ambiguous[Instrument.OPEN_HIHAT.value] == [2]


def test_stacked_ensemble_config_rejects_unknown_models_and_invalid_kernels():
    reference = CheckpointReference(model_version="fixture", sha256="0" * 64)
    rules = {
        instrument.value: StackedEnsembleRule(
            strategy="convex",
            model_weights={"missing": 1},
            threshold=0.5,
            peak_distance_frames=1,
        )
        for instrument in TRAINING_CLASSES
    }
    with pytest.raises(TrainingError, match="unknown models"):
        StackedEnsembleConfig(
            model_version="fixture-stack",
            models={"available": reference},
            rules=rules,
        )
    with pytest.raises(TrainingError, match="odd-length"):
        StackedEnsembleRule(
            strategy="convex",
            model_weights={"available": 1},
            threshold=0.5,
            peak_distance_frames=1,
            temporal_kernel=(1, 1),
        )
    with pytest.raises(TrainingError, match="must be set together"):
        StackedEnsembleRule(
            strategy="convex",
            model_weights={"available": 1},
            threshold=0.5,
            peak_distance_frames=1,
            post_blend_model="available",
        )


def test_stacked_ensemble_config_loads_post_blend(tmp_path: Path):
    rules = {
        instrument.value: {
            "strategy": "convex",
            "modelWeights": {"base": 1},
            "threshold": 0.5,
            "peakDistanceFrames": 1,
        }
        for instrument in TRAINING_CLASSES
    }
    rules[TRAINING_CLASSES[0].value]["postBlend"] = {
        "model": "specialist",
        "strategy": "logit",
        "weight": 0.25,
    }
    path = tmp_path / "stack.json"
    path.write_text(
        json.dumps(
            {
                "schemaVersion": 2,
                "modelVersion": "fixture-stack",
                "models": {
                    "base": {"modelVersion": "base", "sha256": "0" * 64},
                    "specialist": {
                        "modelVersion": "specialist",
                        "sha256": "1" * 64,
                    },
                },
                "familyConflictMargins": {"HIHAT": 1.25},
                "rules": rules,
            }
        ),
        encoding="utf-8",
    )
    loaded = StackedEnsembleConfig.load(path)
    rule = loaded.rules[TRAINING_CLASSES[0].value]
    assert rule.post_blend_model == "specialist"
    assert rule.post_blend_strategy == "logit"
    assert rule.post_blend_weight == 0.25
    assert loaded.family_conflict_margins == {"HIHAT": 1.25}

    with pytest.raises(TrainingError, match="unknown exclusive family"):
        StackedEnsembleConfig(
            model_version="fixture-stack",
            models=loaded.models,
            rules=loaded.rules,
            family_conflict_margins={"CYMBAL": 1.0},
        )

    probabilities = np.full((2, len(TRAINING_CLASSES)), 0.5)
    with pytest.raises(TrainingError, match="missing stacked ensemble probabilities"):
        blend_stacked_probabilities({"base": probabilities}, loaded.rules)
