import hashlib
import json
import wave
from pathlib import Path

import numpy as np
import pytest
from drumscribe_music import Instrument

from drumscribe_ml.calibration import calibrate_confidence
from drumscribe_ml.lifecycle import (
    PreparationConfig,
    augmentation_recipe,
    prepare_dataset,
    read_pcm_wav,
)
from drumscribe_ml.manifest import DatasetLicense, DatasetManifest, DatasetSource, DatasetTrack
from drumscribe_ml.training import (
    TRAINING_CLASSES,
    TrainingConfig,
    TrainingError,
    _dilate_targets,
    _match_frames,
    _peak_frames,
    _training_batches,
    experiment_metadata,
)


def _write_wav(path: Path, *, frequency: float = 110) -> None:
    sample_rate = 8_000
    timeline = np.arange(sample_rate, dtype=np.float32) / sample_rate
    samples = (np.sin(2 * np.pi * frequency * timeline) * 0.25 * 32767).astype("<i2")
    path.parent.mkdir(parents=True)
    with wave.open(str(path), "wb") as target:
        target.setnchannels(1)
        target.setsampwidth(2)
        target.setframerate(sample_rate)
        target.writeframes(samples.tobytes())


def _write_24_bit_wav(path: Path) -> None:
    values = np.array([-8_388_608, -1, 0, 1, 8_388_607], dtype=np.int64)
    encoded = (values & 0xFFFFFF).astype(np.uint32)
    octets = np.column_stack(
        (encoded & 0xFF, (encoded >> 8) & 0xFF, (encoded >> 16) & 0xFF)
    ).astype(np.uint8)
    with wave.open(str(path), "wb") as target:
        target.setnchannels(1)
        target.setsampwidth(3)
        target.setframerate(8_000)
        target.writeframes(octets.tobytes())


def _manifest(root: Path) -> DatasetManifest:
    audio = root / "audio" / "take.wav"
    annotation = root / "annotations" / "take.json"
    _write_wav(audio)
    annotation.parent.mkdir(parents=True)
    annotation.write_text(
        json.dumps(
            [
                {"midiNote": 36, "onsetSeconds": 0.1, "velocity": 100},
                {"label": "snare", "onsetSeconds": 0.5, "velocity": 88},
            ]
        ),
        encoding="utf-8",
    )
    license_record = DatasetLicense(
        "CC0-1.0",
        "https://creativecommons.org/publicdomain/zero/1.0/",
        True,
        "Generated by the DrumScribe test suite",
    )
    return DatasetManifest(
        DatasetSource("Generated test audio", "1", "https://example.test", license_record),
        (
            DatasetTrack(
                "take",
                "performance",
                "audio/take.wav",
                "annotations/take.json",
                1,
                hashlib.sha256(audio.read_bytes()).hexdigest(),
            ),
        ),
    )


def test_preparation_is_reproducible_and_caches_real_features(tmp_path):
    dataset = tmp_path / "dataset"
    manifest = _manifest(dataset)
    config = PreparationConfig(
        seed="release-1",
        sample_rate=8_000,
        frame_length=256,
        hop_length=80,
        mel_bands=24,
        augmentation_variants=1,
    )
    prepared = prepare_dataset(
        manifest,
        dataset_root=dataset,
        output_root=tmp_path / "prepared",
        config=config,
    )
    payload = json.loads(prepared.read_text())
    assert len(payload["records"]) == 2
    assert payload["records"][0]["groupId"] == "performance"
    canonical = json.loads(Path(payload["records"][0]["annotationPath"]).read_text())
    assert [row["instrument"] for row in canonical["events"]] == ["KICK", "SNARE"]
    features = np.load(payload["records"][0]["featurePath"])["features"]
    assert features.ndim == 2 and features.shape[1] == 24
    original, _ = read_pcm_wav(dataset / "audio/take.wav")
    augmented, _ = read_pcm_wav(Path(payload["records"][1]["audioPath"]))
    assert not np.array_equal(original, augmented)
    assert augmentation_recipe("release-1", "take", 1) == augmentation_recipe(
        "release-1", "take", 1
    )


def test_calibration_and_training_metadata_are_versioned(tmp_path):
    logits = np.array([[3.0, -2.0], [-2.0, 2.0], [1.0, -1.0]])
    targets = np.array([[1, 0], [0, 1], [1, 0]])
    result = calibrate_confidence(logits, targets)
    assert result.macro_f1 == pytest.approx(1)
    assert len(result.thresholds) == 2
    config = TrainingConfig("prepared.json", str(tmp_path), "drumscribe-events-0.1.0")
    metadata = experiment_metadata(
        config,
        {"dataset": {"name": "test", "version": "1"}, "datasetManifestHash": "abc"},
    )
    assert metadata["modelVersion"] == "drumscribe-events-0.1.0"
    assert metadata["datasetManifestHash"] == "abc"
    with pytest.raises(TrainingError):
        TrainingConfig("prepared.json", str(tmp_path), "bad/version")
    moe = TrainingConfig(
        "prepared.json",
        str(tmp_path),
        "drumscribe-events-moe-0.1.0",
        architecture="spectral_moe",
        moe_experts=8,
        moe_top_k=2,
    )
    assert moe.architecture == "spectral_moe"
    with pytest.raises(TrainingError, match="top-k"):
        TrainingConfig(
            "prepared.json",
            str(tmp_path),
            "invalid-moe",
            architecture="spectral_moe",
            moe_experts=2,
            moe_top_k=3,
        )


def test_training_targets_and_validation_are_onset_tolerant_and_multilabel():
    targets = np.zeros((8, 2), dtype=np.float32)
    targets[3, :] = 1
    dilated = _dilate_targets(targets, 1)
    assert dilated[:, 0].tolist() == [0, 0, 1, 1, 1, 0, 0, 0]
    probabilities = np.array([0.1, 0.6, 0.8, 0.7, 0.2])
    assert _peak_frames(probabilities, threshold=0.5) == [2]
    assert _match_frames([4, 10], [5, 20], tolerance=2) == (1, 1, 1)
    assert set(TRAINING_CLASSES) == set(Instrument)


def test_pcm_reader_decodes_signed_24_bit_audio(tmp_path):
    path = tmp_path / "24-bit.wav"
    _write_24_bit_wav(path)
    samples, sample_rate = read_pcm_wav(path)
    assert sample_rate == 8_000
    assert samples[:, 0].tolist() == pytest.approx([-1, -1 / 8_388_608, 0, 1 / 8_388_608, 1])


def test_training_batches_pad_and_mask_only_real_frames():
    features = np.ones((5, 3), dtype=np.float32)
    onsets = np.zeros((5, 2), dtype=np.float32)
    velocities = np.zeros_like(onsets)
    batches = list(_training_batches(features, onsets, velocities, 3, 2))
    feature_batch, _, _, valid = batches[0]
    assert feature_batch.shape == (2, 3, 3)
    assert valid[:, :, 0].tolist() == [[1, 1, 1], [1, 1, 0]]
