import hashlib
import json
import wave
from pathlib import Path

import numpy as np
import pytest

from drumscribe_ml.calibration import calibrate_confidence
from drumscribe_ml.lifecycle import (
    PreparationConfig,
    augmentation_recipe,
    prepare_dataset,
    read_pcm_wav,
)
from drumscribe_ml.manifest import DatasetLicense, DatasetManifest, DatasetSource, DatasetTrack
from drumscribe_ml.training import TrainingConfig, TrainingError, experiment_metadata


def _write_wav(path: Path, *, frequency: float = 110) -> None:
    sample_rate = 8_000
    timeline = np.arange(sample_rate, dtype=np.float32) / sample_rate
    samples = (np.sin(2 * np.pi * frequency * timeline) * 0.25 * 32767).astype("<i2")
    path.parent.mkdir(parents=True)
    with wave.open(str(path), "wb") as target:
        target.setnchannels(1)
        target.setsampwidth(2)
        target.setframerate(sample_rate)
        target.writeframes(samples.tobytes())


def _manifest(root: Path) -> DatasetManifest:
    audio = root / "audio" / "take.wav"
    annotation = root / "annotations" / "take.json"
    _write_wav(audio)
    annotation.parent.mkdir(parents=True)
    annotation.write_text(
        json.dumps(
            [
                {"midiNote": 36, "onsetSeconds": 0.1, "velocity": 100},
                {"label": "snare", "onsetSeconds": 0.5, "velocity": 88},
            ]
        ),
        encoding="utf-8",
    )
    license_record = DatasetLicense(
        "CC0-1.0",
        "https://creativecommons.org/publicdomain/zero/1.0/",
        True,
        "Generated by the DrumScribe test suite",
    )
    return DatasetManifest(
        DatasetSource("Generated test audio", "1", "https://example.test", license_record),
        (
            DatasetTrack(
                "take",
                "performance",
                "audio/take.wav",
                "annotations/take.json",
                1,
                hashlib.sha256(audio.read_bytes()).hexdigest(),
            ),
        ),
    )


def test_preparation_is_reproducible_and_caches_real_features(tmp_path):
    dataset = tmp_path / "dataset"
    manifest = _manifest(dataset)
    config = PreparationConfig(
        seed="release-1",
        sample_rate=8_000,
        frame_length=256,
        hop_length=80,
        mel_bands=24,
        augmentation_variants=1,
    )
    prepared = prepare_dataset(
        manifest,
        dataset_root=dataset,
        output_root=tmp_path / "prepared",
        config=config,
    )
    payload = json.loads(prepared.read_text())
    assert len(payload["records"]) == 2
    assert payload["records"][0]["groupId"] == "performance"
    canonical = json.loads(Path(payload["records"][0]["annotationPath"]).read_text())
    assert [row["instrument"] for row in canonical["events"]] == ["KICK", "SNARE"]
    features = np.load(payload["records"][0]["featurePath"])["features"]
    assert features.ndim == 2 and features.shape[1] == 24
    original, _ = read_pcm_wav(dataset / "audio/take.wav")
    augmented, _ = read_pcm_wav(Path(payload["records"][1]["audioPath"]))
    assert not np.array_equal(original, augmented)
    assert augmentation_recipe("release-1", "take", 1) == augmentation_recipe(
        "release-1", "take", 1
    )


def test_calibration_and_training_metadata_are_versioned(tmp_path):
    logits = np.array([[3.0, -2.0], [-2.0, 2.0], [1.0, -1.0]])
    targets = np.array([[1, 0], [0, 1], [1, 0]])
    result = calibrate_confidence(logits, targets)
    assert result.macro_f1 == pytest.approx(1)
    assert len(result.thresholds) == 2
    config = TrainingConfig("prepared.json", str(tmp_path), "drumscribe-events-0.1.0")
    metadata = experiment_metadata(
        config,
        {"dataset": {"name": "test", "version": "1"}, "datasetManifestHash": "abc"},
    )
    assert metadata["modelVersion"] == "drumscribe-events-0.1.0"
    assert metadata["datasetManifestHash"] == "abc"
    with pytest.raises(TrainingError):
        TrainingConfig("prepared.json", str(tmp_path), "bad/version")
